### ISSUE TITLE
Imouto Paradise 3 (Japanese Version)

### ISSUE THREAD

**Issue by DSHinako21** [marcussacana/RLDManager#4]
can't find this text in japanese ver (please check pic)
![unknown](https://user-images.githubusercontent.com/24751784/76147185-3ced4900-60cc-11ea-857d-61072a09604a.png)

**Comment by marcussacana** [comment]
upload the script plz

**Comment by marcussacana** [comment]
First, about the name, as asked in the [#1](https://github.com/marcussacana/Specific-Games/issues/1), looks like this game don't use text as name, but images, take a look in this part of the script.

![image](https://user-images.githubusercontent.com/10576957/85540257-27ede480-b5ed-11ea-9642-6c7d1a54a43a.png)

**Comment by marcussacana** [comment]
Fixed, Update your plugin and test it, if works close the issue.
Also, keep atention because this can happen again, in that case you can re-open the issue or create a new one.

**Comment by DSHinako21** [comment]
still don't see the name of char
![image](https://user-images.githubusercontent.com/24751784/85574231-ca937b00-b660-11ea-87a8-920aa9964200.png)

**Comment by marcussacana** [comment]
> First, about the name, as asked in the [#1](https://github.com/marcussacana/Specific-Games/issues/1), looks like this game don't use text as name, but images, take a look in this part of the script.
> 
> ![image](https://user-images.githubusercontent.com/10576957/85540257-27ede480-b5ed-11ea-9642-6c7d1a54a43a.png)

**Comment by DSHinako21** [comment]
You're wrong bruh

![image](https://user-images.githubusercontent.com/24751784/85711988-0cc8c500-b712-11ea-9a2d-8163bbd27c99.png)

**Comment by marcussacana** [comment]
At least the name isn't in the script, I near the dialog, probably have a .rld only for the names or is embbed in the game executable.

**Comment by marcussacana** [comment]
The names are in the defChars.rld
I don't will add support to edit the DefChars.rld automatically
![2020-06-25 14_11_37-010 Editor - C__Users_Marcus_Documents_My Games_妹ぱらだいす！３_rld_defChara rld crypt](https://user-images.githubusercontent.com/10576957/85767062-032d6600-b6ee-11ea-8f9d-0c5e5d519303.png)
Anyway, You can manually edit,
Use the new 'crypt' feature to decrypt the defChars.rld, then open with a hex editor in SJIS, then just edit any name that you see, don't care about add or remove characters, probabbly that don't will break anything.

**Comment by DSHinako21** [comment]
Okay, will try later, tks first
